from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

main_btns = ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = KeyboardButton('Расписание 🗓️')
btn2 = KeyboardButton('События ✨')
btn3 = KeyboardButton('Задания 📚')
btn4 = KeyboardButton('Полезная информация ℹ️')
main_btns.add(btn1).add(btn2).add(btn3).add(btn4)

kb_choice = ReplyKeyboardMarkup(resize_keyboard=True)
btn_c1 = KeyboardButton('Я учитель')
btn_c2 = KeyboardButton('Я ученик')
btn_c3 = KeyboardButton('Я родитель')
kb_choice.add(btn_c1).add(btn_c2).add(btn_c3)

cl_buttons = ReplyKeyboardMarkup(resize_keyboard=True)
btn_c1 = KeyboardButton('Понедельник')
btn_c2 = KeyboardButton('Вторник')
btn_c3 = KeyboardButton('Среда')
btn_c4 = KeyboardButton('Четверг')
btn_c5 = KeyboardButton('Пятница')
btn_c6 = KeyboardButton('Суббота')
btn_c7 = KeyboardButton('Назад')
cl_buttons.insert(btn_c1).insert(btn_c2)
cl_buttons.insert(btn_c3).insert(btn_c4)
cl_buttons.insert(btn_c5).insert(btn_c6)
cl_buttons.insert(btn_c7)


high_choice = InlineKeyboardMarkup(resize_keyboard=True)
h1 = InlineKeyboardButton(text='Экономика', url="https://postupi.online/vuzi/vuzspec-economic/")
h2 = InlineKeyboardButton(text='Гуманитарные науки', url="https://postupi.online/vuzi/vuzspec-humanities/")
h3 = InlineKeyboardButton(text='Педагогика', url="https://postupi.online/vuzi/vuzspec-pedagogical/")
h4 = InlineKeyboardButton(text='Лингвистика', url="https://postupi.online/vuzi/vuzspec-linguistic/")
h5 = InlineKeyboardButton(text='Медицина', url="https://postupi.online/vuzi/razdel-medicina-i-zdravoohranenie/vuzspec-linguistic/")
h6 = InlineKeyboardButton(text='Физика и ИКТ', url="https://postupi.online/vuzi/vuzspec-technical/")
high_choice.add(h1).add(h2).add(h3).add(h4).add(h5).add(h6)

inline_kb1 = InlineKeyboardMarkup(row_width=1)
inline_btn_1 = InlineKeyboardButton(text='Тинькофф Образование', url='https://fintech.tinkoff.ru/school/')
inline_btn_2 = InlineKeyboardButton(text='Яндекс Лицей', url='https://lyceum.yandex.ru/')
inline_btn_3 = InlineKeyboardButton(text='Код Будущего', url='https://free-code.ru/')
inline_kb1 = InlineKeyboardMarkup().add(inline_btn_1).add(inline_btn_2).add(inline_btn_3)

inf = ReplyKeyboardMarkup(resize_keyboard=True)
inf1 = KeyboardButton('Подборка вузов')
inf2 = KeyboardButton('Подготовка к олимпиадам')
inf3 = KeyboardButton('Обучающие курсы')
inf4 = KeyboardButton('Полезные ссылки')
inf5 = KeyboardButton('Назад')
inf.add(inf1).add(inf2).add(inf3).add(inf4).add(inf5)

links_kb = InlineKeyboardMarkup(row_width=1)
link1 = InlineKeyboardButton(text='Решу ЕГЭ', url='https://ege.sdamgia.ru/?id&ysclid=lmn86qzj1y774532591')
link2 = InlineKeyboardButton(text='LI Chess', url='https://lichess.org')
links_kb.add(link1).add(link2)
